Repository shinhan-project/shinhan1, pull requests merged in 2025-01, with the labels that each got.

#10 Yoonkyung
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewService.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewServiceImpl.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewVO.java
  hanokproject/src/main/resources/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/review/review.jsp
  hanokproject/src/main/webapp/js/rating.js
Labels: feat

#13 Feat: 리뷰리스트 페이지 구현
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewVO.java
  hanokproject/src/main/resources/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/review/reviews.jsp
Labels: feat

#15 owner_dash페이지
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationController.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationService.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationServiceImpl.java
  hanokproject/src/main/resources/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_dash.jsp
Labels: feat

#16 Feat: 예약 정보에 대한 리뷰 생성
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationVO.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewService.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewServiceImpl.java
  hanokproject/src/main/resources/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/review/review.jsp
Labels: feat

#17 Feat: 리뷰작성시 예약정보 나타나도록 추가
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationService.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationServiceImpl.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationVO.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewService.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewServiceImpl.java
  hanokproject/src/main/resources/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/src/main/resources/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/review/review.jsp
Labels: feat

#19 사장님 프로필 수정페이지 완료!
  hanokproject/src/main/java/kr/co/hanokproject/customer/CustomerServiceImpl.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerController.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerService.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerServiceImpl.java
  hanokproject/src/main/resources/kr/co/hanokproject/owner/OwnerMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/customer/profile.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_dash.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_listings.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_profile.jsp
Labels: feat

#22 Review 추가, 리스트 UI 변경
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationVO.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewVO.java
  hanokproject/src/main/resources/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/src/main/resources/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/review/review.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/reviews.jsp
  hanokproject/src/main/webapp/images/hanoks/hanok11.jpg
  hanokproject/target/classes/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/target/m2e-wtp/web-resources/META-INF/maven/kr.co/test/pom.properties
Labels: fix

#24 고객 예약상세페이지 작성 완료
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationController.java
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationVO.java
  hanokproject/src/main/java/kr/co/hanokproject/room/RoomService.java
  hanokproject/src/main/resources/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/customer/bookingdetail.jsp
  hanokproject/src/main/webapp/WEB-INF/views/customer/mybookings.jsp
  hanokproject/src/main/webapp/images/element/creditcard.png
  hanokproject/src/main/webapp/images/element/creditcard1.png
  hanokproject/src/main/webapp/images/element/kakaopay.png
  hanokproject/src/main/webapp/images/element/naverpay.png
  hanokproject/target/classes/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/target/m2e-wtp/web-resources/META-INF/maven/kr.co/test/pom.properties
Labels: feat

#25 민정, 예진, 윤경 파트 완료
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewService.java
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewServiceImpl.java
  hanokproject/src/main/resources/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/src/main/resources/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/customer/mybookings.jsp
  hanokproject/src/main/webapp/WEB-INF/views/customer/profile.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_dash.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_listings.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_profile.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/owner_revie.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/owner_review.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/reviews.jsp
  hanokproject/target/classes/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/target/m2e-wtp/web-resources/META-INF/maven/kr.co/test/pom.properties
Labels: feat

#26 리뷰 작성된 예약 create reivew 버튼 숨김
  hanokproject/src/main/java/kr/co/hanokproject/reservation/ReservationVO.java
  hanokproject/src/main/resources/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/customer/mybookings.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/owner_revie.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/owner_review.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/reviews.jsp
  hanokproject/target/classes/kr/co/hanokproject/admin/AdminMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/customer/CustomerMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/hanok/HanokMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/owner/OwnerMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/reservation/ReservationMapper.xml
  hanokproject/target/classes/kr/co/hanokproject/review/ReviewMapper.xml
  hanokproject/target/classes/log4j.xml
  hanokproject/target/classes/log4jdbc.log4j2.properties
  hanokproject/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  hanokproject/target/m2e-wtp/web-resources/META-INF/maven/kr.co/test/pom.properties
  hanokproject/target/m2e-wtp/web-resources/META-INF/maven/kr.co/test/pom.xml
  hanokproject/target/test-classes/log4j.xml
Labels: ⭐feature

#43 Yejinsong
  hanokproject/src/main/java/kr/co/hanokproject/hanok/HanokController.java
  hanokproject/src/main/java/kr/co/hanokproject/hanok/HanokMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/hanok/HanokService.java
  hanokproject/src/main/java/kr/co/hanokproject/hanok/HanokServiceImple.java
  hanokproject/src/main/java/kr/co/hanokproject/hanok/HanokVO.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerController.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerMapper.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerService.java
  hanokproject/src/main/java/kr/co/hanokproject/owner/OwnerServiceImpl.java
  hanokproject/src/main/resources/kr/co/hanokproject/hanok/HanokMapper.xml
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_authorization.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_dash.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_rooms.jsp
Labels: ⭐feature

#46 review ui 수정, owner리뷰조회 @sessionattribute로 변경
  hanokproject/src/main/java/kr/co/hanokproject/review/ReviewController.java
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_authorization.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_dash.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_listings.jsp
  hanokproject/src/main/webapp/WEB-INF/views/owner/owner_profile.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/owner_review.jsp
  hanokproject/src/main/webapp/WEB-INF/views/review/reviews.jsp
Labels: 🔧fix
